### ISSUE TITLE
missing /api/checklogin

### ISSUE THREAD

**Issue by bxrbeq** [felixstaude/Offchat-Highscore#1]
bei der Anmeldung muss eine einzigartige Session-ID generiert werden. Diese wird dann mit der login verification mitgesendent und wird im client als session-cookie gespeichert. Dieser wird vom Backend bei jedem neuen Seitenaufruf gecheckt. So wird verhindert, dass Clients ohne login auf gesperrte Seiten zugreifen können

**Comment by felixstaude** [comment]
Also soll quasi beim einloggen ein session cookie erstellt werden, gespeichert werden und beim seitenwechsel jedes mal abgefragt werden?
hat die SessionID irgendwelche vorgaben, ob diese nur bestimme Zeichen enthalten darf oder eine bestimmte länge haben sollte?
Soll die SessionID bei jedem Login generiert werden?

**Comment by felixstaude** [comment]
hat die SessionID irgendwelche vorgaben, ob diese nur bestimme Zeichen enthalten darf oder eine bestimmte länge haben sollte?

**Comment by bxrbeq** [comment]
ja, danke. das hast du sehr gut gemacht. Issue kann geschlossen werden 👍
